# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

serviceAccount: yunikorn-admin

image:
  repository: yunikorn/yunikorn-scheduler-k8s
  tag: latest
  pullPolicy: Always

web_image:
  repository: yunikorn/yunikorn-web
  tag: latest
  pullPolicy: Always

curl_image:
  repository: curlimages/curl
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 9080
  port_web: 9889

resources:
  requests:
    cpu: 200m
    memory: 1Gi
  limits:
    cpu: 4
    memory: 2Gi

# When this flag is true, the admission controller will be installed along with the scheduler.
# When this flag is false, the admission controller will not be installed.
# Once the admission controller is installed, all traffic will be routing to yunikorn.
embedAdmissionController: false

#
# ------------------------------------------------------------------------
# Please choose one configuration from following two for yunikorn
# Use "CMD + /" to comment-out or uncomment a block before the deployment
# ------------------------------------------------------------------------
#

# Use this configuration to automatically map K8s namespaces to yunikorn queues
configuration: |
  partitions:
    -
      name: default
      placementrules:
        - name: tag
          value: namespace
          create: true
      queues:
        - name: root
          submitacl: '*'

# Use this configuration to configure absolute capacities for yunikorn queues
#configuration: |
#  partitions:
#    -
#      name: default
#      queues:
#        -
#          name: root
#          submitacl: '*'
#          queues:
#            -
#              name: advertisement
#              resources:
#                guaranteed:
#                  memory: 500000
#                  vcore: 50000
#                max:
#                  memory: 800000
#                  vcore: 80000
#            -
#              name: search
#              resources:
#                guaranteed:
#                  memory: 400000
#                  vcore: 40000
#                max:
#                  memory: 600000
#                  vcore: 60000
#            -
#              name: sandbox
#              resources:
#                guaranteed:
#                  memory: 100000
#                  vcore: 10000
#                max:
#                  memory: 100000
#                  vcore: 10000

